server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080
spring:
  datasource:
    url: ${DATABASE_URL}?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100
    open-in-view: false
logging.level:
  org.hibernate.SQL: debug
  # org.hibernate.type: trace

cloud:
  aws:
    s3:
      bucket: fundering-img
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
#    credentials:
#      profile-name: default